### ISSUE TITLE
Add set of paint brush tools

### ISSUE THREAD

**Issue by Rosethorns** [codetaylor/artisan-tools-1.16#2]
It would be great if there were a set of paintbrushes for tools preferably the paddle style

**Comment by codetaylor** [comment]
When you say 'paddle style', are you referring to this:

![image](https://user-images.githubusercontent.com/1240716/108104183-d42e8080-703f-11eb-8bcd-c8c8f7b3344f.png)

**Comment by Rosethorns** [comment]
yis
